name: merge
on: 
   push:
   workflow_dispatch:
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}  #get_personnel_access_token https://github.com/settings/tokens
      - name: Merge upstream
        run: |
          export token=${{ secrets.GH_TOKEN }} && echo $token && sleep 120
          git config --global user.name 'jha-oajka'
          git config --global user.email 'jha-oajka@users.noreply.github.com'
          git pull --unshallow  
          git remote add upstream https://github.com/amitstudydude/RDP_Linux.git
          git fetch upstream
          git checkout main
          git merge --no-edit upstream/main
          git push origin main
          cd .github/workflows
          sudo unlink /etc/localtime
          sudo ln -s /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
          date > .txt
          git config --global user.name 'jha-oajka'
          git config --global user.email 'jha-oajka@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git add -A
          git commit -am "Automated report"
          git push origin main
          #curl \
          ##-X POST \
          ###-H "Accept: application/vnd.github.v3+json" \
          ### -H "Authorization: token $token" \
          ####https://api.github.com/repos/amitstudydude/runner/merge-upstream \
          ### -d '{"branch":"main"}'
